services:
  api:
    build:
      context: ./API
    image: image-resizing-api
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
    ports:
      - ${EXPOSED_API_PORT}:${API_PORT}
  
  ui:
    build:
      context: ./UI
    image: image-resizing-ui
    environment:
      - UI_HOST=${UI_HOST}
      - UI_PORT=${UI_PORT}
      - API_PORT=${EXPOSED_API_PORT}
    ports:
      - ${EXPOSED_UI_PORT}:${UI_PORT}