services:
  api:
    build:
      context: ./API
    image: image-resizing-api
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - UI_HOST=${UI_HOST}
      - UI_PORT=${UI_PORT}
    ports:
      - 40000:${API_PORT}
  
  ui:
    build:
      context: ./UI
    image: image-resizing-ui
    environment:
      - UI_HOST=${UI_HOST}
      - UI_PORT=${UI_PORT}
    ports:
      - 40001:${UI_PORT}